CREATE DATABASE shard1 DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;
CREATE DATABASE shard2 DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;

CREATE TABLE `t_order_0` (
	`order_id` INT(11) NULL DEFAULT NULL,
	`user_id` INT(11) NULL DEFAULT NULL,
	`status` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='utf8_bin'
ENGINE=INNODB;

CREATE TABLE `t_order_1` (
	`order_id` INT(11) NULL DEFAULT NULL,
	`user_id` INT(11) NULL DEFAULT NULL,
	`status` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='utf8_bin'
ENGINE=INNODB;


CREATE TABLE `t_user` (
	`user_id` INT(11) NULL DEFAULT NULL,
	`user_name` VARCHAR(50) NULL DEFAULT NULL,
	`age` INT(3) NULL DEFAULT NULL
)
COLLATE='utf8_bin'
ENGINE=INNODB;